name: github pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  schedule:
    # Run at 4am Pacific time
    - cron: "0 12 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: yarn install

      - name: Download data
        run: yarn fetch-data

      - name: Build
        run: yarn build --public-url '/bc-covid-map'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
